version: '3.7'
services:
  # database:
  #   image: 'postgres:12.11'
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
  #     POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
  #     POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
  app:
    build: .
    # depends_on:
    #   - database
    volumes:
      - ${CODE_DIR_LOCAL}:${CODE_DIR_IMAGE}:rw
      - ${SSH_DIR_LOCAL}:${SSH_DIR_IMAGE}:rw
      - ${VIM_SETUP_LOCAL}:${VIM_SETUP_IMAGE}:ro
      - ${DOT_CONFIG_LOCAL}:${DOT_CONFIG_IMAGE}:ro
      - ${GIT_CONFIG_LOCAL}:${GIT_CONFIG_IMAGE}:ro
